---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен соблюдать законадательные акты
  - Пользователь должен иметь возможность удалять товары из корзины
  - Пользователь должен видеть итоговую стоимость товара
  - Пользователь должен видеть наличие товара
  - Пользователь должен иметь возможность отфильтровать товар в наличии
  - Пользователь должен иметь визуальное подтверждение добавления товара в корзину
  - В корзине указывается итоговая сумма выбранного товара с учетом всех скидок
  - При оформлении заказа необходимо подтвердить заказ
  - После оформления заказа открывается страница оплаты
  - У пользователя должна быть возможность выбора оплаты товара
  - Итоговое оформление заказа происходит после указания контактных данных пользователя
  - Сайт должен соответсвовать макету от дизайнера
  - Сайт явялется SPA 